"""Render the daily portfolio brief as Markdown.

The brief is written for a human reading it before the open. Order matters:
what breached a rule, then what to do, then the numbers behind it, then the
questions the research pass still has to answer.
"""

from __future__ import annotations

from datetime import datetime, timezone

from connectors.schwab.portfolio import Portfolio
from connectors.schwab.signals import (
    ADD,
    EXIT,
    HOLD,
    NO_DATA,
    TRIM,
    WATCH,
    Verdict,
)

DISCLAIMER = (
    "Generated by a rules engine over price and position data. It is analysis, "
    "not investment advice, and it is not a substitute for a licensed adviser. "
    "No order was placed, modified, or cancelled to produce this brief."
)

VERDICT_LABEL = {
    ADD: "Add",
    HOLD: "Hold",
    WATCH: "Watch",
    TRIM: "Trim",
    EXIT: "Exit review",
    NO_DATA: "No data",
}


def _money(value: float | None) -> str:
    if value is None:
        return "—"
    return f"${value:,.2f}"


def _pct(value: float | None, digits: int = 1) -> str:
    """Signed percentage, for anything that is a change or a return."""
    if value is None:
        return "—"
    return f"{value:+.{digits}%}"


def _share(value: float | None, digits: int = 1) -> str:
    """Unsigned percentage, for shares and levels.

    A 47% position weight is not "+47%" — the plus sign implies a change
    that did not happen. Negatives still print their own sign.
    """
    if value is None:
        return "—"
    return f"{value:.{digits}%}"


def _num(value: float | None, digits: int = 0) -> str:
    if value is None:
        return "—"
    return f"{value:,.{digits}f}"


def _summary_section(portfolio: Portfolio) -> list[str]:
    lines = [
        "## Portfolio",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Account | `{portfolio.account_label}` ({portfolio.account_type}) |",
        f"| Account equity | {_money(portfolio.liquidation_value)} |",
        f"| Invested | {_money(portfolio.invested_value)} |",
        f"| Cash | {_money(portfolio.cash)} ({_share(portfolio.cash_weight)}) |",
        f"| Positions | {len(portfolio.equity_holdings)} |",
        f"| Day P/L | {_money(portfolio.day_pl)} |",
        f"| Unrealized P/L | {_money(portfolio.unrealized_pl)} "
        f"({_pct(portfolio.unrealized_pl_pct)}) |",
        f"| Largest position | {_share(portfolio.largest_weight)} of invested |",
        f"| Concentration | {portfolio.concentration_index:.2f} "
        f"(~{portfolio.effective_positions:.1f} equal-weight names) |",
        "",
    ]
    return lines


def _alerts_section(alerts: list[str]) -> list[str]:
    if not alerts:
        return ["## Guardrails", "", "No portfolio-level guardrail breaches.", ""]
    lines = ["## Guardrails", ""]
    lines.extend(f"- {alert}" for alert in alerts)
    lines.append("")
    return lines


def _actions_section(verdicts: list[Verdict]) -> list[str]:
    lines = ["## Actions", ""]
    actionable = [v for v in verdicts if v.verdict in (ADD, TRIM, EXIT)]
    if not actionable:
        lines.append("Nothing crossed an action threshold. Every position reads hold or watch.")
        lines.append("")
        return lines

    for verdict in actionable:
        lines.append(
            f"### {VERDICT_LABEL[verdict.verdict]} — {verdict.symbol} "
            f"(score {verdict.score:+.0f}, {_share(verdict.weight)} of invested)"
        )
        lines.append("")
        for breach in verdict.guardrail_breaches:
            lines.append(f"- **Guardrail:** {breach}")
        for reason in verdict.reasons[:6]:
            lines.append(f"- {reason}")
        lines.append("")
    return lines


def _holdings_section(verdicts: list[Verdict]) -> list[str]:
    lines = [
        "## Holdings",
        "",
        "| Symbol | Verdict | Score | Weight | Value | Week | Month | Quarter | "
        "Unreal. | RSI | vs 200d | Off high |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---|---:|",
    ]
    for v in verdicts:
        m = v.metrics
        if m.last_close is not None and m.slow_ma is not None:
            trend = "above" if m.last_close > m.slow_ma else "below"
        else:
            trend = "—"
        lines.append(
            f"| {v.symbol} | {VERDICT_LABEL[v.verdict]} | {v.score:+.0f} | "
            f"{_share(v.weight)} | {_money(v.market_value)} | {_pct(m.week_return)} | "
            f"{_pct(m.month_return)} | {_pct(m.quarter_return)} | "
            f"{_pct(v.unrealized_pl_pct)} | {_num(m.rsi)} | {trend} | "
            f"{_share(m.drawdown_from_high)} |"
        )
    lines.append("")
    return lines


def _research_section(verdicts: list[Verdict]) -> list[str]:
    pending = [v for v in verdicts if v.needs_corroboration and v.research_questions]
    if not pending:
        return []
    lines = [
        "## Research queue",
        "",
        "Mechanical scores read price only. Answer these before acting on anything above.",
        "",
    ]
    for verdict in pending:
        lines.append(f"**{verdict.symbol}** — {VERDICT_LABEL[verdict.verdict]}")
        lines.extend(f"- {question}" for question in verdict.research_questions)
        lines.append("")
    return lines


def _gaps_section(verdicts: list[Verdict]) -> list[str]:
    gapped = [v for v in verdicts if v.data_gaps]
    if not gapped:
        return []
    lines = ["## Data gaps", ""]
    for verdict in gapped:
        lines.append(f"- **{verdict.symbol}**: " + "; ".join(verdict.data_gaps))
    lines.append("")
    return lines


def render_brief(
    portfolio: Portfolio,
    verdicts: list[Verdict],
    alerts: list[str],
    generated_at: datetime | None = None,
) -> str:
    """Assemble the full Markdown brief."""
    stamp = (generated_at or datetime.now(timezone.utc)).astimezone()
    counts: dict[str, int] = {}
    for verdict in verdicts:
        counts[verdict.verdict] = counts.get(verdict.verdict, 0) + 1
    # Report the tally along the conviction ladder, not alphabetically, so
    # "2 exit review" is never buried between "add" and "hold".
    tally = ", ".join(
        f"{counts[name]} {VERDICT_LABEL[name].lower()}"
        for name in (ADD, HOLD, WATCH, TRIM, EXIT, NO_DATA)
        if counts.get(name)
    )

    lines = [
        f"# Portfolio brief — {stamp:%Y-%m-%d %H:%M %Z}",
        "",
        f"{len(verdicts)} positions scored: {tally or 'none'}.",
        "",
    ]
    lines += _alerts_section(alerts)
    lines += _actions_section(verdicts)
    lines += _summary_section(portfolio)
    lines += _holdings_section(verdicts)
    lines += _research_section(verdicts)
    lines += _gaps_section(verdicts)
    lines += ["---", "", f"_{DISCLAIMER}_", ""]
    return "\n".join(lines)
